/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.Datatype.ui.contentassist

import at.ac.tuwien.big.xmltext.Datatype.ui.contentassist.AbstractDatatypeProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class DatatypeProposalProvider extends AbstractDatatypeProposalProvider {
}
