/*
 * generated by Xtext
 */
/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.Datatype.serializer;


class DatatypeSyntacticSequencer extends AbstractDatatypeSyntacticSequencer {
}
