/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.idIdref;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IdIdrefUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return at.ac.tuwien.big.xmltext.idIdref.ui.internal.IdIdrefActivator.getInstance().getInjector("at.ac.tuwien.big.xmltext.idIdref.IdIdref");
	}
	
}
