/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.idIdref.validation;

import at.ac.tuwien.big.xmltext.idIdref.validation.AbstractIdIdrefValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IdIdrefValidator extends AbstractIdIdrefValidator {
}
