/*
 * generated by Xtext
 */
/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.idIdref.serializer;


class IdIdrefSyntacticSequencer extends AbstractIdIdrefSyntacticSequencer {
}
