/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.Datatype.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DatatypeUiModule extends at.ac.tuwien.big.xmltext.Datatype.ui.AbstractDatatypeUiModule {
	public DatatypeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
