/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.Datatype;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DatatypeStandaloneSetup extends DatatypeStandaloneSetupGenerated{

	public static void doSetup() {
		new DatatypeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

