/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.Datatype;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DatatypeRuntimeModule extends at.ac.tuwien.big.xmltext.Datatype.AbstractDatatypeRuntimeModule {

}
