/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.idIdref.serializer;

import at.ac.tuwien.big.xmltext.idIdref.serializer.AbstractIdIdrefSemanticSequencer;

@SuppressWarnings("all")
public class IdIdrefSemanticSequencer extends AbstractIdIdrefSemanticSequencer {
}
