/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.idIdref.serializer;

import at.ac.tuwien.big.xmltext.idIdref.serializer.AbstractIdIdrefSyntacticSequencer;

@SuppressWarnings("all")
public class IdIdrefSyntacticSequencer extends AbstractIdIdrefSyntacticSequencer {
}
