/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.Datatype.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.ac.tuwien.big.xmltext.Datatype.ui.internal.DatatypeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DatatypeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DatatypeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DatatypeActivator.getInstance().getInjector(DatatypeActivator.AT_AC_TUWIEN_BIG_XMLTEXT_DATATYPE_DATATYPE);
	}
	
}
