/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.idIdref.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class IdIdrefOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
