/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.idIdref;

import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.xtext.example.demo.syntax.ExampleAntlrTokenToAttributeIdMapper;
import org.xtext.example.demo.syntax.ExampleHighlightingConfiguration;
import org.xtext.example.demo.syntax.ExampleSemanticHighlightingCalculator;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IdIdrefRuntimeModule extends at.ac.tuwien.big.xmltext.idIdref.AbstractIdIdrefRuntimeModule {
	
	@Override
	public void configure(Binder binder) {
		// TODO Auto-generated method stub
		super.configure(binder);
		
		binder.bind(IHighlightingConfiguration.class).to(ExampleHighlightingConfiguration.class);
		binder.bind(AbstractAntlrTokenToAttributeIdMapper.class).to(ExampleAntlrTokenToAttributeIdMapper.class);
		binder.bind(ISemanticHighlightingCalculator.class).to(ExampleSemanticHighlightingCalculator.class);
	}
}
