/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.Datatype.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DatatypeAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/ac/tuwien/big/xmltext/Datatype/parser/antlr/internal/InternalDatatype.tokens");
	}
}
