/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.idIdref.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IdIdrefUiModule extends at.ac.tuwien.big.xmltext.idIdref.ui.AbstractIdIdrefUiModule {
	public IdIdrefUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
