/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.idIdref.ui.contentassist

import at.ac.tuwien.big.xmltext.idIdref.ui.contentassist.AbstractIdIdrefProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class IdIdrefProposalProvider extends AbstractIdIdrefProposalProvider {
}
