/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.idIdref.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IdIdrefAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/ac/tuwien/big/xmltext/idIdref/parser/antlr/internal/InternalIdIdref.tokens");
	}
}
